description: |
  Trigger a build job in jenkins "with parameters".
parameters:
  exec:
    description: The name of custom executor to use
    type: executor
    default: default
  user_id:
    description: Jenkins user name with permissions to the job
    type: env_var_name
    default: JENKINS_USER
  access_token:
    description: "Jenkins user's access token"
    type: env_var_name
    default: JENKINS_TOKEN
  server_url:
    description: "Jenkins endpoint"
    type: env_var_name
    default: JENKINS_SERVER_URL
  job_path:
    type: string
    description: |
      path to job to be triggered. For example: team-name/job/deploys/job/repo
  job_params:
    type: string
    description: |
      any additional parameters to send to the job
    default: "DEPLOY_ENV=staging&DOCKER_VERSION=${CIRCLE_TAG}"
executor: << parameters.exec >>
steps:
  - run:
      name: Trigger build via curl
      command: |
        curl  -X POST --user <<parameters.user_id>>:<<parameters.access_token>> -d "<<parameters.job_params>>" <<parameters.server_url>>/job/<<parameters.job_path>>/buildWithParameters
