description: |
  If you have a standard project with helm configuration, you can use this orb to run through
  a common helm workflow of packaging and pushing to external (github) helm repository.

  Extra configuration can be put in a local config file. See more information about the config options 
  [https://github.com/helm/chart-testing](https://github.com/helm/chart-testing#configuration)

  An example config file will look like: [helmTestConfig.yaml]
    ```
    helm-extra-args: --timeout 600
    validate-chart-schema: false
    validate-maintainers: false
    chart-dirs: helm
    excluded-charts: example
    ```

usage:
  version: 2.1

  orbs:
    ta-helm: travelaudience/helm@0.1.0

  workflows:
    build_and_test:
      jobs:
        - ta-helm/validate:
          chart_test_config: .circleci/extraConfigFile.yamls
        - ta-helm/package_and_push:
            requires:
              - ta-helm/validate
            context: git-push-config
            chart_git_repo: git@github.com:your-org/helmrepo.git
