version: 2.1

executors:
  cli:
    docker:
      - image: circleci/circleci-cli:0.1.2709

jobs:
  lint:
    docker:
      - image: singapore/lint-condo
    steps:
      - checkout
      - run:
          'yamllint .'

  build:
    executor: cli
    steps:
      - checkout
      - run: "echo -e \"token: placeholder\nverbose: false > ~/.circleci/cli.yml\""
      - run: bash scripts/validate-orbs.sh


workflows:
  version: 2
  main:
    jobs:
      - lint
      - build

      # TODO: add publishing....
