version: 2.1

deploy_tag_filter: &deploy_tag_filter
  branches:
    ignore: /.*/
  tags:
    only: /^[a-z,-]+-[0-9]+(\.[0-9]+){2}([0-9A-Za-z-+.]?)+/


orbs:
  cli: circleci/circleci-cli@0.1.2
  orb-tools: circleci/orb-tools@8.27.5

jobs:
  pre-orb-promotion-check:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: Check that the tag is a mapped to master branch commit
          command: |
            git clone "$CIRCLE_REPOSITORY_URL" repository
            cd repository
            git branch --contains ${CIRCLE_SHA1} | grep "master"

  publish-orb-into-production:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: >
            Publish orb at to production, based on $CIRCLE_TAG
          command: |
            ORB_NAME="$(echo $CIRCLE_TAG | sed 's/-[0-9].*//')"
            VERSION="$(echo $CIRCLE_TAG | sed 's/.*\-\([0-9]\)/\1/')"
            circleci config pack src/$ORB_NAME > ${ORB_NAME}.yaml
            circleci orb publish "$ORB_NAME.yaml" "travelaudience/${ORB_NAME}@${VERSION}" --token ${CIRCLE_ORB_TOKEN}


workflows:
  version: 2
  orb-validate-dev-push:
    jobs:
      # Code Climate
      - orb-tools/lint:
          lint-dir: src/code-climate
          name: code-climate-lint
      - orb-tools/pack:
          source-dir: src/code-climate
          destination-orb-path: code-climate.yaml
          name: code-climate-pack
          workspace-path: code-climate.yaml
      - orb-tools/publish-dev:
          name: code-climate-dev-publish
          context: orb-publishing
          orb-name: travelaudience/code-climate
          orb-path: workspace/code-climate.yaml
          alpha-version-ref: "dev:$CIRCLE_BRANCH"
          publish-token-variable: CIRCLE_ORB_TOKEN
          requires:
            - code-climate-lint
            - code-climate-pack

      # Docker
      - orb-tools/lint:
          lint-dir: src/docker
          name: docker-lint
      - orb-tools/pack:
          source-dir: src/docker
          destination-orb-path: docker.yaml
          name: docker-pack
          workspace-path: docker.yaml
      - orb-tools/publish-dev:
          name: docker-dev-publish
          context: orb-publishing
          orb-name: travelaudience/docker
          orb-path: workspace/docker.yaml
          alpha-version-ref: "dev:$CIRCLE_BRANCH"
          publish-token-variable: CIRCLE_ORB_TOKEN
          requires:
            - docker-lint
            - docker-pack

      # Go
      - orb-tools/lint:
          lint-dir: src/go
          name: go-lint
      - orb-tools/pack:
          source-dir: src/go
          destination-orb-path: go.yaml
          name: go-pack
          workspace-path: go.yaml
      - orb-tools/publish-dev:
          name: go-dev-publish
          context: orb-publishing
          orb-name: travelaudience/go
          orb-path: workspace/go.yaml
          alpha-version-ref: "dev:$CIRCLE_BRANCH"
          publish-token-variable: CIRCLE_ORB_TOKEN
          requires:
            - go-lint
            - go-pack

      # Helm
      - orb-tools/lint:
          lint-dir: src/helm
          name: helm-lint
      - orb-tools/pack:
          source-dir: src/helm
          destination-orb-path: helm.yaml
          name: helm-pack
          workspace-path: helm.yaml
      - orb-tools/publish-dev:
          name: helm-dev-publish
          context: orb-publishing
          orb-name: travelaudience/helm
          orb-path: workspace/helm.yaml
          alpha-version-ref: "dev:$CIRCLE_BRANCH"
          publish-token-variable: CIRCLE_ORB_TOKEN
          requires:
            - helm-lint
            - helm-pack

      # Deploy
      - orb-tools/lint:
          lint-dir: src/deploy
          name: deploy-lint
      - orb-tools/pack:
          source-dir: src/deploy
          destination-orb-path: deploy.yaml
          name: deploy-pack
          workspace-path: deploy.yaml
      - orb-tools/publish-dev:
          name: deploy-dev-publish
          context: orb-publishing
          orb-name: travelaudience/deploy
          orb-path: workspace/deploy.yaml
          alpha-version-ref: "dev:$CIRCLE_BRANCH"
          publish-token-variable: CIRCLE_ORB_TOKEN
          requires:
            - deploy-lint
            - deploy-pack

      # GCloud
      - orb-tools/lint:
          lint-dir: src/gcloud
          name: gcloud-lint
      - orb-tools/pack:
          source-dir: src/gcloud
          destination-orb-path: gcloud.yaml
          name: gcloud-pack
          workspace-path: gcloud.yaml
      - orb-tools/publish-dev:
          name: gcloud-dev-publish
          context: orb-publishing
          orb-name: travelaudience/gcloud
          orb-path: workspace/gcloud.yaml
          alpha-version-ref: "dev:$CIRCLE_BRANCH"
          publish-token-variable: CIRCLE_ORB_TOKEN
          requires:
            - gcloud-lint
            - gcloud-pack

  orb-promotion:
    jobs:
      - pre-orb-promotion-check:
          filters: *deploy_tag_filter
      - publish-orb-into-production:
          context: orb-publishing
          requires:
            - pre-orb-promotion-check
          filters: *deploy_tag_filter
