version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.2
  orb-tools: circleci/orb-tools@8.27.5

jobs:
  pre-orb-promotion-check:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: Check that the tag is a mapped to master branch commit
          command: |
            git clone "$CIRCLE_REPOSITORY_URL" repository
            cd repository
            git branch --contains ${CIRCLE_SHA1} | grep "master"

  publish-orb-into-production:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: >
            Publish orb at to production, based on $CIRCLE_TAG
          command: |
            ORB_NAME="$(echo $CIRCLE_TAG | sed 's/-v[0-9].*/\1/')"
            VERSION="$(echo $CIRCLE_TAG | sed 's/.*\-/\1/')"
            circleci orb publish "src/$ORB_NAME/orb.yaml" "travelaudience/${ORB_NAME}@${VERSION}" --token ${CIRCLE_ORB_TOKEN}



workflows:
  version: 2
  orb-validate-dev-push:
    jobs:
      - orb-tools/lint:
          lint-dir: src/code-climate
          name: code-climate-lint
      - orb-tools/pack:
          source-dir: src/code-climate
          destination-orb-path: code-climate.yaml
          name: code-climate-pack
          workspace-path: code-climate.yaml

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: travelaudience/code-climate
          orb-path: workspace/code-climate.yaml
          alpha-version-ref: "dev:$CIRCLE_BRANCH"
          publish-token-variable: CIRCLE_ORB_TOKEN
          requires:
            - code-climate-lint
            - code-climate-pack

  orb-promotion:
    jobs:
      - pre-orb-promotion-check:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[a-z,-]+-v[0-9]+(\.[0-9]+)*$/
      - publish-orb-into-production:
          context: orb-publishing
          requires:
            - pre-orb-promotion-check
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[a-z,-]+-v[0-9]+(\.[0-9]+)*$/
