description: |
  Package and push charts that have changed. Pushed to github chart repository.
parameters:
  chart_git_repo:
    description: The github repo that keeps packaged charts
    type: string
  exec:
    description: The name of custom executor to use
    type: executor
    default: helm-tester
executor: << parameters.exec >>
steps:
  - checkout
  - package
  - push:
      chart_git_repo: <<parameters.chart_git_repo>>
