description: |
  Package and push charts that have changed. Pushed to github chart repository.
parameters:
  chart_git_repo:
    description: The github repo that keeps packaged charts
    type: string
  chart_test_config:
    description: |
      Path to local config file with settings to be used by Chart Tester
      For example:
        helm-extra-args: --timeout 600
        validate-maintainers: false
    type: string
    default: ".circleci/helmTestConfig.yaml"
  chart_dir_override:
    description: |
      Due to 'ct list-changed' not working on master (see https://github.com/helm/chart-testing/pull/159)
      Need get changed charts through git command.
      Defaulting to searching in 'helm' dir to look for changes.
    type: string
    default: "helm"
  chart_stable_branch:
    description: The branch that should be used to store a chart in stable repository
    type: string
    default: "master"
  exec:
    description: The name of custom executor to use
    type: executor
    default: helm-tester
executor: << parameters.exec >>
steps:
  - checkout
  - package:
      chart_test_config: <<parameters.chart_test_config>>
      chart_dir_override: <<parameters.chart_dir_override>>
      chart_stable_branch: <<parameters.chart_stable_branch>>
  - push:
      chart_git_repo: <<parameters.chart_git_repo>>
      chart_stable_branch: <<parameters.chart_stable_branch>>
