description: |
  Install charts into local k8s cluster (install is currently disabled).
executors:
  chart-testing-exec:
    machine: true
parameters:
  chart_test_config:
    description: |
      Path to local config file with settings to be used by Chart Tester
      For example:
        helm-extra-args: --timeout 600
        validate-maintainers: false
    type: string
    default: ".circleci/helmTestConfig.yaml"
  exec:
    description: The name of custom executor to use
    type: executor
    default: chart-testing-exec
executor: << parameters.exec >>
steps:
  - checkout
  - install:
      chart_test_config: <<parameters.chart_test_config>>
