description: |
  Install charts into local k8s cluster (install is currently disabled).
parameters:
  chart_test_config:
    description: |
      Path to local config file with settings to be used by Chart Tester
      For example:
        helm-extra-args: --timeout 600
        validate-maintainers: false
    type: string
    default: ".circleci/helmTestConfig.yaml"
  exec:
    description: The name of custom executor to use
    type: executor
    default: chart-testing-exec
executor: << parameters.exec >>
steps:
  - checkout
  - run: |
      curl -sSLo chart-testing "https://github.com/helm/chart-testing/releases/download/v2.4.0/chart-testing_2.4.0_linux_amd64.tar.gz"
      sudo mkdir /usr/local/bin/chart-testing
      sudo tar -C /usr/local/bin/chart-testing -zxvf chart-testing
      ls -al /usr/local/bin
      sudo chmod +x /usr/local/bin/chart-testing/ct
      export PATH=$PATH:"/usr/local/bin/chart-testing"
      echo $PATH
      ct version
  - install:
      chart_test_config: <<parameters.chart_test_config>>
