description: Set env var with either branch name OR git tag
steps:
  - run: |
          if [ ! -z "$CIRCLE_TAG" ];
          then
            echo 'export CHANGE_NAME="$(echo "$CIRCLE_TAG" | sed -r 's/[\/=_#]+/-/g')"' >> $BASH_ENV
          elif [ ! -z "$CIRCLE_BRANCH" ];
          then
            echo 'export CHANGE_NAME="$(echo "$CIRCLE_BRANCH" | sed -r 's/[\/=_#]+/-/g')"' >> $BASH_ENV
          fi
          source $BASH_ENV
          echo $CHANGE_NAME
