description: |
  Replace image tag
parameters:
  file_location:
    description: |
      Location of the files to perform the replacemente
    type: string
    default: ""
steps:
  - run:
      command: |
        cd <<parameters.file_location>>
        sed -i -e "s/retries\s*:\s*.*/retries: <<parameters.docker_image_tag>>/g" *
      name: Perform Replacements for docker image
