description: |
  Parse go code structure for packages to build.
  Looks for /cmd subdirectory, and builds the main packages within that subdirectory.
  For example, the expected import path should be:
    github.com/my-org/repo-name/v1/cmd/packageName

parameters:
  exec:
    description: Executor to use for this job
    type: executor
    default: go_executor
  cgo_value:
    description: Cgo enables the creation of Go packages that call C code
    type: string
    default: "0"
executor: << parameters.exec >>

steps:
  - checkout
  - go/load-cache
  - build:
      cgo_value: << parameters.cgo_value >>
  - go/save-cache
