description: |
  If files changed, run a helm install in kind to test that the chart can be installed
  !!NOTE: this is not functional at this time!! docker within docker is not enabled at this time
parameters:
  chart_test_config:
    description: |
      Path to local config file with settings to be used by Chart Tester
      For example:
        helm-extra-args: --timeout 600
        validate-maintainers: false
    type: string
    default: ".circleci/helmTestConfig.yaml"
  kind_version:
    description: Version of Kind to be used
    type: string
    default: "v0.7.0"
  k8s_version:
    description: K8s version to be run with kind
    type: string
    default: "v1.15.0"
  helm_version:
    description: helm version to be run with kind
    type: string
    default: "v2.16.1"
steps:
  - run:
      command: |
        source $BASH_ENV
        if [ "$(ct list-changed --config ./circleci/helmTestConfig.yaml)" ];
        then
          echo "Installing kubectl...""
          curl -LO https://storage.googleapis.com/kubernetes-release/release/<<parameters.k8s_version>>/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          echo "Installing helm..."
          curl -LO "https://get.helm.sh/helm-<<parameters.helm_version>>-linux-amd64.tar.gz"
          sudo mkdir -p "/usr/local/helm-<<parameters.helm_version>>"
          sudo tar -xzf "helm-<<parameters.helm_version>>-linux-amd64.tar.gz" -C "/usr/local/helm-<<parameters.helm_version>>"
          sudo ln -s "/usr/local/helm-<<parameters.helm_version>>/linux-amd64/helm" /usr/local/bin/helm
          echo "Installing kind..."
          curl -sSLo kind "https://github.com/kubernetes-sigs/kind/releases/download/<<parameters.kind_version>>/kind-linux-amd64"
          chmod +x kind
          sudo mv kind /usr/local/bin/kind
          echo "Creating cluster..."
          kind create cluster --name "chart-testing" --config .circleci/kind-config.yaml --image "kindest/node:<<parameters.k8s_version>>" --wait 60s

          echo $(kubectl get nodes)
          kubectl delete storageclass standard
          kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
          kubectl --namespace kube-system create sa tiller
          kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
          helm init --service-account tiller --upgrade --wait
          echo $(helm version)
          ct install --config ./circleci/helmTestConfig.yaml
        else
          echo "no helm changes to test"
        fi
      name: "[helm] Install"
