description: Run helm validation with Chart Tester
parameters:
  chart_test_config: &chart_test_config
    description: |
      Path to local config file with settings to be used by Chart Tester
      For example:
        helm-extra-args: --timeout 600
        validate-maintainers: false
    type: string
    default: ".circleci/helmTest.yaml"
steps:
  - run: "ct lint --config <<parameters.chart_test_config>>"
