description: "Package the helm chart(s)"
parameters:
  chart_test_config:
    description: |
      Path to local config file with settings to be used by Chart Tester
      For example:
        helm-extra-args: --timeout 600
        validate-maintainers: false
    type: string
    default: ".circleci/helmTestConfig.yaml"
  chart_package_path:
    description: The path where packaged charts will be saved (defaults to a local, relative path)
    type: string
    default: ".cr-release-packages"
steps:
  - run:
      shell: /bin/sh
      command: |
        helm init --client-only  || true  # this step is required for helm v2
        helm version -c
        if [ $CT_CHART_REPOS ] ; then
            IFS=', ' read -r -a array \<<<  $CT_CHART_REPOS
            for i in "${array[@]}"; do
                # echo "$i"
                repo_name=$(echo "$i" | cut -d'=' -f1)
                repo_url=$(echo "$i" | cut -d'=' -f2)
                helm repo add $repo_name $repo_url
            done
        fi
        rm -rf <<parameters.chart_package_path>>; mkdir <<parameters.chart_package_path>>
        ct list-changed --config <<parameters.chart_test_config>> | while IFS= read -r chart ; do
            chart=$(echo $chart | sed 's/.*Skipping...//g')
            if [ "$chart" == "" ]; then
              continue
            fi

            echo "Packaging chart: '$chart'..."
            helm dependency build "$chart"

            # set the version different for incubator
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              helm package "$chart" --destination <<parameters.chart_package_path>>
            else
              ver=$(helm inspect chart "$chart" | grep version | cut -d' ' -f2)
              [[ -z $CIRCLE_TAG ]] && BRANCH="$CIRCLE_BRANCH" || BRANCH="$CIRCLE_TAG"
              echo "packaging $chart with version: ${ver}-${BRANCH}"
              helm package "$chart" -u --version "${ver}-${BRANCH}" --destination .cr-release-packages
            fi

            echo "'$chart' packaged"
            echo "-----"
        done
      name: "[helm] Package"
