executor: clair-scanner/default
parameters:
  docker-username:
    description: Name of environment variable storing your Docker username
    type: env_var_name
    default: GCR_USERNAME
  docker-password:
    description: Name of environment variable storing your Docker password
    type: env_var_name
    default: GCR_PASSWORD
  registry:
    description: Name of environment variable storing the registry host
    type: env_var_name
    default: GCR_REGISTRY
steps:
  - attach_workspace:
      at: /tmp
  - run: find /tmp/image-names -type f -name '*.txt' -exec cat {} + >> /images.file
  - run: docker login -u "$<<parameters.docker-username>>" -p "$<<parameters.docker-password>>"  "$<<parameters.registry>>"
  - clair-scanner/scan:
      image_file: /images.file
